### ISSUE TITLE
weird request

### ISSUE THREAD

**Issue by JustinBrow** [p0w3rsh3ll/ADK#2]
Heya! I don't suppose you have the 8.1 ADK files archived somewhere?

**Comment by p0w3rsh3ll** [comment]
Hello,
I have ADK 8.1 files from 2014.
ADK for 8.1 should be same for 2012 R2 and should still be available. 2012 R2 reaches end of life in October 2023.

**Comment by JustinBrow** [comment]
Could you share them with me? Microsoft pulled them from their website.  
I'm looking for ADK 8.1 specifically, rather than the current version, because the server I have at home was our old decommissioned 2012 r2 box.

**Comment by p0w3rsh3ll** [comment]
Here's the download link available for 7 days: https://transfert.free.fr/yXabTZ8

password for the download : adk8dot1

sha256 of adk81.zip: BF25AEB1D88418AD9DDA22BFE0DB37DBBD4F8460E325DA21952F6E9A9BB77EAC

**Comment by p0w3rsh3ll** [comment]
@JustinBrow see above the link...

**Comment by JustinBrow** [comment]
Thank you!
